version: '3.8'

services:
  db:
    image: neo4j:4.4-community
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/pdbe_demo

  cli:
    build: .
    environment:
      - NEO4J_URI=bolt://db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=pdbe_demo
    depends_on:
      - db
    volumes:
      - ./sample:/app/sample
